name = "Quick Vanilla Server"
author = "piuvas"
version = "1.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7df0b0eda1a94e48598621a2f16dcf38bc504e51ea8c689862c7d9eaf2778873"

[versions]
minecraft = "1.18.2"
quilt = "0.16.1-beta.3"
