name = "Quick Vanilla Server"
author = "piuvas"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "02b90f4564a76bbc8f2397fc1e3d3ceecd06b349f42b0e62a45e6ba04a2472af"

[versions]
minecraft = "1.19"
quilt = "0.17.0-beta.2"
