name = "Quick Vanilla Server"
author = "piuvas"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b3c893c55cfeb357972df8883be68840db614f31a3a6c11444729ff577202a4e"

[versions]
minecraft = "1.19"
quilt = "0.17.0-beta.2"
