name = "Quick Vanilla Server"
author = "piuvas"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ec454aee9dde99c7eec610ebcdef7653815203d4a397e8fa41b39e4a56052045"

[versions]
minecraft = "1.19"
quilt = "0.17.0-beta.2"
