name = "Quick Vanilla Server"
author = "piuvas"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1e1e388de82bc95065edc701509967a826519fe9474a4bb847e2c8dc4421f54a"

[versions]
minecraft = "1.19"
quilt = "0.17.0-beta.2"
