name = "Quick Vanilla Server"
author = "piuvas"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "285a3f3e49fc65f67a645d1c793e09c6c47d8ca7f0dd19d9205623254d3df9f2"

[versions]
minecraft = "1.19"
quilt = "0.17.0-beta.2"
