name = "Quick Vanilla Server"
author = "piuvas"
version = "2.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e655da4ef7de040ca8e491ebe760450ff04d87c2fb919ae49774efd26fb461ea"

[versions]
minecraft = "1.19"
quilt = "0.17.0-beta.2"
