name = "Quick Vanilla Server"
author = "piuvas"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "824648e7f834c205eba35e2ce1539ae102f4203ff8e6c19695ab1b7ed5f526cf"

[versions]
minecraft = "1.19"
quilt = "0.17.0-beta.2"
