name = "Quick Vanilla Server"
author = "piuvas"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "09c9a799cab4250abd65883ff60fdc9913b76f22eef21bf41cfb8a16fc03051c"

[versions]
minecraft = "1.19"
quilt = "0.17.0-beta.2"
