name = "Quick Vanilla Server"
author = "piuvas"
version = "2.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c2bb05f51519af9f9d448425dea2b07779cfae098b57056a299946cd77abbe84"

[versions]
minecraft = "1.19"
quilt = "0.17.0-beta.2"
