name = "Quick Vanilla Server"
author = "piuvas"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "452989b7d38582f14dd70dc01a4f57aff095b27e24b95261b2457f5023b43551"

[versions]
minecraft = "1.19"
quilt = "0.17.0-beta.2"
