name = "Quick Vanilla Server"
author = "piuvas"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "23bf033c430488686f6bf09917102846bd7af9c17963188ec3f03c0bf252abcd"

[versions]
minecraft = "1.19"
quilt = "0.17.0-beta.2"
