name = "Quick Vanilla Server"
author = "piuvas"
version = "2.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1bf8154b12face6c46b47747660905f48688e9a3298fc08412b516bf57179c39"

[versions]
minecraft = "1.19"
quilt = "0.17.0-beta.2"
