name = "Quick Vanilla Server"
author = "piuvas"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a73d053d6c55d44b9636bed80d793d9f21a3f40c4b2149c7cf5f38d1fda5e874"

[versions]
minecraft = "1.19"
quilt = "0.17.0-beta.2"
