name = "Quick Vanilla Server"
author = "piuvas"
version = "1.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4e03aab59d9babcb0545ec2ddfb0168ec0fcb080f5bdd0b957c8f7bd9fe048e4"

[versions]
minecraft = "1.18.2"
quilt = "0.16.1-beta.3"
