name = "Quick Vanilla Server"
author = "piuvas"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fd507660b006885a742a98de1b2d65024a1eca8afba3bcc4797226ed3e9920e6"

[versions]
minecraft = "1.19"
quilt = "0.17.0-beta.2"
