name = "Quick Vanilla Server"
author = "piuvas"
version = "2.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "abee759e840bc8fd43b4e919e3f27d3172f8302e7c28ffcf80b4d70fe7f4fb5f"

[versions]
minecraft = "1.19"
quilt = "0.17.0-beta.2"
