name = "Quick Vanilla Server"
author = "piuvas"
version = "1.0.1"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "82a4c78a8458299bdd595a9d439ab86ac0b519cb1adcb8d67591c39dbc9bdfa9"

[versions]
minecraft = "1.18.2"
quilt = "0.16.1-beta.3"
