name = "Concurrent Chunk Management Engine (Fabric)"
filename = "c2me-fabric-mc1.19-0.2.0+alpha.7.56.jar"
side = "both"

[download]
url = "https://cdn.modrinth.com/data/VSNURh3q/versions/0.2.0+alpha.7.56+1.19/c2me-fabric-mc1.19-0.2.0%2Balpha.7.56.jar"
hash-format = "sha1"
hash = "f981892afce7a8f28baf15964014f0dccff7f316"

[update]
[update.modrinth]
mod-id = "VSNURh3q"
version = "KFecXkCR"
