name = "Very Many Players (Fabric)"
filename = "vmp-fabric-mc1.19-0.2.0+beta.6.23-all.jar"
side = "both"

[download]
url = "https://cdn.modrinth.com/data/wnEe9KBa/versions/0.2.0+beta.6.23+1.19/vmp-fabric-mc1.19-0.2.0%2Bbeta.6.23-all.jar"
hash-format = "sha1"
hash = "b8bdf9d167644acd1d072ca7938472295fa418cb"

[update]
[update.modrinth]
mod-id = "wnEe9KBa"
version = "5A7EoPlS"
