on:
    workflow_dispatch:
jobs:
    update:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Setup Go environment
              uses: actions/setup-go@v3.1.0
            - name: Setup Packwiz
              run: go install github.com/packwiz/packwiz@latest
            - name: Update
              run: packwiz update --all
            - uses: stefanzweifel/git-auto-commit-action@v4
