name: 'update'
on:
    workflow_dispatch:
jobs:
    update:
        runs-on: ubuntu-latest
        steps:
            - name: Update Packwiz Mods
              uses: derspyy/packwiz-update-action@v1.0
