name: Update
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Update Packwiz Mods
        uses: derspyy/packwiz-update-action@v1.0
